## This file is a general .xdc for the Arty A7 Rev. D
## To use it in a project: ddr5 phy


####################################################################
####################### Clock signal ###############################
####################################################################

create_clock -period 20.000 -name clk_i -waveform {0.000 10.000} [get_ports clk_i]
set_property -dict { PACKAGE_PIN N15  IOSTANDARD LVCMOS33 }  [get_ports clk_i]

####################################################################
#################### Clock uncertainty #############################
####################################################################

set_clock_uncertainty -setup 4.000 [get_clocks *]
set_clock_uncertainty -hold 2.00 [get_clocks *]

####################################################################
############### set input/output delay on ports ####################
####################################################################

set_input_delay -clock [get_clocks *] 0.500 [get_ports {dfi_address_p0[0] dfi_address_p0[1] dfi_address_p0[2] dfi_address_p0[3] dfi_address_p0[4] dfi_address_p0[5] dfi_address_p0[6] dfi_address_p0[7] dfi_address_p0[8] dfi_address_p0[9] dfi_address_p0[10] dfi_address_p0[11] dfi_address_p0[12] dfi_address_p0[13] dfi_address_p1[0] dfi_address_p1[1] dfi_address_p1[2] dfi_address_p1[3] dfi_address_p1[4] dfi_address_p1[5] dfi_address_p1[6] dfi_address_p1[7] dfi_address_p1[8] dfi_address_p1[9] dfi_address_p1[10] dfi_address_p1[11] dfi_address_p1[12] dfi_address_p1[13] dfi_address_p2[0] dfi_address_p2[1] dfi_address_p2[2] dfi_address_p2[3] dfi_address_p2[4] dfi_address_p2[5] dfi_address_p2[6] dfi_address_p2[7] dfi_address_p2[8] dfi_address_p2[9] dfi_address_p2[10] dfi_address_p2[11] dfi_address_p2[12] dfi_address_p2[13] dfi_address_p3[0] dfi_address_p3[1] dfi_address_p3[2] dfi_address_p3[3] dfi_address_p3[4] dfi_address_p3[5] dfi_address_p3[6] dfi_address_p3[7] dfi_address_p3[8] dfi_address_p3[9] dfi_address_p3[10] dfi_address_p3[11] dfi_address_p3[12] dfi_address_p3[13] dfi_cs_n_p0[0] dfi_cs_n_p0[1] dfi_cs_n_p1[0] dfi_cs_n_p1[1] dfi_cs_n_p2[0] dfi_cs_n_p2[1] dfi_cs_n_p3[0] dfi_cs_n_p3[1] dfi_reset_n_p0[0] dfi_reset_n_p0[1] dfi_reset_n_p1[0] dfi_reset_n_p1[1] dfi_reset_n_p2[0] dfi_reset_n_p2[1] dfi_reset_n_p3[0] dfi_reset_n_p3[1] dfi_wrdata_en_p0 dfi_wrdata_en_p1 dfi_wrdata_en_p2 dfi_wrdata_en_p3 dfi_wrdata_mask_p0[0] dfi_wrdata_mask_p1[0] dfi_wrdata_mask_p2[0] dfi_wrdata_mask_p3[0] dfi_wrdata_p0[0] dfi_wrdata_p0[1] dfi_wrdata_p0[2] dfi_wrdata_p0[3] dfi_wrdata_p0[4] dfi_wrdata_p0[5] dfi_wrdata_p0[6] dfi_wrdata_p0[7] dfi_wrdata_p1[0] dfi_wrdata_p1[1] dfi_wrdata_p1[2] dfi_wrdata_p1[3] dfi_wrdata_p1[4] dfi_wrdata_p1[5] dfi_wrdata_p1[6] dfi_wrdata_p1[7] dfi_wrdata_p2[0] dfi_wrdata_p2[1] dfi_wrdata_p2[2] dfi_wrdata_p2[3] dfi_wrdata_p2[4] dfi_wrdata_p2[5] dfi_wrdata_p2[6] dfi_wrdata_p2[7] dfi_wrdata_p3[0] dfi_wrdata_p3[1] dfi_wrdata_p3[2] dfi_wrdata_p3[3] dfi_wrdata_p3[4] dfi_wrdata_p3[5] dfi_wrdata_p3[6] dfi_wrdata_p3[7] enable_i rst_i}]

set_output_delay -clock [get_clocks *] 0.000 [get_ports * -filter direction==out]

####################################################################
################## I/O ports connections ###########################
####################################################################

# input ports

set_property -dict { PACKAGE_PIN U17  IOSTANDARD LVCMOS33 }  [get_ports {CA[11]}]
set_property -dict { PACKAGE_PIN T15  IOSTANDARD LVCMOS33 }  [get_ports {CA[4]}]
set_property -dict { PACKAGE_PIN R17  IOSTANDARD LVCMOS33 }  [get_ports {CA[0]}]
set_property -dict { PACKAGE_PIN U18  IOSTANDARD LVCMOS33 }  [get_ports {CA[10]}]
set_property -dict { PACKAGE_PIN U16  IOSTANDARD LVCMOS33 }  [get_ports {CA[13]}]
set_property -dict { PACKAGE_PIN V17  IOSTANDARD LVCMOS33 }  [get_ports {CA[12]}]
set_property -dict { PACKAGE_PIN V15  IOSTANDARD LVCMOS33 }  [get_ports {CA[9]}]
set_property -dict { PACKAGE_PIN V16  IOSTANDARD LVCMOS33 }  [get_ports {CA[8]}]
set_property -dict { PACKAGE_PIN R15  IOSTANDARD LVCMOS33 }  [get_ports {CA[2]}]
set_property -dict { PACKAGE_PIN R16  IOSTANDARD LVCMOS33 }  [get_ports {CA[7]}]
set_property -dict { PACKAGE_PIN T16  IOSTANDARD LVCMOS33 }  [get_ports {CA[6]}]
set_property -dict { PACKAGE_PIN T14  IOSTANDARD LVCMOS33 }  [get_ports {CA[5]}]
set_property -dict { PACKAGE_PIN P17  IOSTANDARD LVCMOS33 }  [get_ports {CA[1]}]
set_property -dict { PACKAGE_PIN P15  IOSTANDARD LVCMOS33 }  [get_ports {CA[3]}]
set_property -dict { PACKAGE_PIN T18  IOSTANDARD LVCMOS33 }  [get_ports {CS_n[0]}]
set_property -dict { PACKAGE_PIN R18  IOSTANDARD LVCMOS33 }  [get_ports {CS_n[1]}]
set_property -dict { PACKAGE_PIN B1   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[3]}]
set_property -dict { PACKAGE_PIN D3   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[8]}]
set_property -dict { PACKAGE_PIN D2   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[12]}]
set_property -dict { PACKAGE_PIN E2   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[13]}]
set_property -dict { PACKAGE_PIN F4   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[11]}]
set_property -dict { PACKAGE_PIN F3   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[10]}]
set_property -dict { PACKAGE_PIN E3   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[9]}]
set_property -dict { PACKAGE_PIN D5   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[7]}]
set_property -dict { PACKAGE_PIN D4   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[6]}]
set_property -dict { PACKAGE_PIN A3   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[0]}]
set_property -dict { PACKAGE_PIN B3   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[5]}]
set_property -dict { PACKAGE_PIN B2   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[4]}]
set_property -dict { PACKAGE_PIN A1   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[2]}]
set_property -dict { PACKAGE_PIN A4   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p0[1]}]
set_property -dict { PACKAGE_PIN C1   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[10]}]
set_property -dict { PACKAGE_PIN D7   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[10]}]
set_property -dict { PACKAGE_PIN E7   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[11]}]
set_property -dict { PACKAGE_PIN E6   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[9]}]
set_property -dict { PACKAGE_PIN K2   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p3[9]}]
set_property -dict { PACKAGE_PIN D8   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[7]}]
set_property -dict { PACKAGE_PIN B4   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[12]}]
set_property -dict { PACKAGE_PIN K1   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p3[10]}]
set_property -dict { PACKAGE_PIN H2   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[11]}]
set_property -dict { PACKAGE_PIN J4   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p3[13]}]
set_property -dict { PACKAGE_PIN C5   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[0]}]
set_property -dict { PACKAGE_PIN C7   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[6]}]
set_property -dict { PACKAGE_PIN E1   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[6]}]
set_property -dict { PACKAGE_PIN G6   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[3]}]
set_property -dict { PACKAGE_PIN F1   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[5]}]
set_property -dict { PACKAGE_PIN G2   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[12]}]
set_property -dict { PACKAGE_PIN C6   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[1]}]
set_property -dict { PACKAGE_PIN G4   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[1]}]
set_property -dict { PACKAGE_PIN H4   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[0]}]
set_property -dict { PACKAGE_PIN J3   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p3[11]}]
set_property -dict { PACKAGE_PIN A5   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[4]}]
set_property -dict { PACKAGE_PIN A6   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[5]}]
set_property -dict { PACKAGE_PIN C4   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[13]}]
set_property -dict { PACKAGE_PIN F6   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[4]}]
set_property -dict { PACKAGE_PIN B7   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[3]}]
set_property -dict { PACKAGE_PIN E5   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[8]}]
set_property -dict { PACKAGE_PIN H5   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p3[8]}]
set_property -dict { PACKAGE_PIN B6   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p1[2]}]
set_property -dict { PACKAGE_PIN G3   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[2]}]
set_property -dict { PACKAGE_PIN C2   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[9]}]
set_property -dict { PACKAGE_PIN F5   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[13]}]
set_property -dict { PACKAGE_PIN G1   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[8]}]
set_property -dict { PACKAGE_PIN J2   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p3[12]}]
set_property -dict { PACKAGE_PIN H1   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p2[7]}]
set_property -dict { PACKAGE_PIN H6   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p3[7]}]
set_property -dict { PACKAGE_PIN J5   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p3[6]}]
set_property -dict { PACKAGE_PIN B8   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p3[1]}]
set_property -dict { PACKAGE_PIN A10  IOSTANDARD LVCMOS33 }  [get_ports {dfi_address_p3[5]}]
set_property -dict { PACKAGE_PIN A8   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p3[0]}]
set_property -dict { PACKAGE_PIN A9   IOSTANDARD LVCMOS33 } [get_ports {dfi_address_p3[4]}]
set_property -dict { PACKAGE_PIN C11  IOSTANDARD LVCMOS33 }  [get_ports {dfi_address_p3[3]}]
set_property -dict { PACKAGE_PIN C10  IOSTANDARD LVCMOS33 }  [get_ports {dfi_address_p3[2]}]
set_property -dict { PACKAGE_PIN M2   IOSTANDARD LVCMOS33 } [get_ports {dfi_cs_n_p0[1]}]
set_property -dict { PACKAGE_PIN N2   IOSTANDARD LVCMOS33 } [get_ports {dfi_cs_n_p0[0]}]
set_property -dict { PACKAGE_PIN K3   IOSTANDARD LVCMOS33 } [get_ports {dfi_cs_n_p1[0]}]
set_property -dict { PACKAGE_PIN N1   IOSTANDARD LVCMOS33 } [get_ports {dfi_cs_n_p1[1]}]
set_property -dict { PACKAGE_PIN M1   IOSTANDARD LVCMOS33 } [get_ports {dfi_cs_n_p3[1]}]
set_property -dict { PACKAGE_PIN L1   IOSTANDARD LVCMOS33 } [get_ports {dfi_cs_n_p2[0]}]
set_property -dict { PACKAGE_PIN L3   IOSTANDARD LVCMOS33 } [get_ports {dfi_cs_n_p2[1]}]
set_property -dict { PACKAGE_PIN K6   IOSTANDARD LVCMOS33 } [get_ports {dfi_cs_n_p3[0]}]
set_property -dict { PACKAGE_PIN V1   IOSTANDARD LVCMOS33 } [get_ports {dfi_reset_n_p0[0]}]
set_property -dict { PACKAGE_PIN U1   IOSTANDARD LVCMOS33 } [get_ports {dfi_reset_n_p0[1]}]
set_property -dict { PACKAGE_PIN U3   IOSTANDARD LVCMOS33 } [get_ports {dfi_wrdata_mask_p0[0]}]
set_property -dict { PACKAGE_PIN K5   IOSTANDARD LVCMOS33 } [get_ports {dfi_reset_n_p2[1]}]
set_property -dict { PACKAGE_PIN V5   IOSTANDARD LVCMOS33 } [get_ports {dfi_wrdata_mask_p3[0]}]
set_property -dict { PACKAGE_PIN L5   IOSTANDARD LVCMOS33 } [get_ports {dfi_reset_n_p1[0]}]
set_property -dict { PACKAGE_PIN L6   IOSTANDARD LVCMOS33 } [get_ports {dfi_reset_n_p1[1]}]
set_property -dict { PACKAGE_PIN U2   IOSTANDARD LVCMOS33 } [get_ports {dfi_wrdata_mask_p1[0]}]
set_property -dict { PACKAGE_PIN M3   IOSTANDARD LVCMOS33 } [get_ports {dfi_reset_n_p3[1]}]
set_property -dict { PACKAGE_PIN U4   IOSTANDARD LVCMOS33 } [get_ports {dfi_reset_n_p3[0]}]
set_property -dict { PACKAGE_PIN L4   IOSTANDARD LVCMOS33 } [get_ports {dfi_reset_n_p2[0]}]
set_property -dict { PACKAGE_PIN V2   IOSTANDARD LVCMOS33 } [get_ports {dfi_wrdata_mask_p2[0]}]
set_property -dict { PACKAGE_PIN C14  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p0[5]}]
set_property -dict { PACKAGE_PIN B14  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p0[7]}]
set_property -dict { PACKAGE_PIN D14  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p0[6]}]
set_property -dict { PACKAGE_PIN G13  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p0[4]}]
set_property -dict { PACKAGE_PIN B13  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p0[3]}]
set_property -dict { PACKAGE_PIN B12  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p0[2]}]
set_property -dict { PACKAGE_PIN C12  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p0[1]}]
set_property -dict { PACKAGE_PIN A11  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p0[0]}]
set_property -dict { PACKAGE_PIN H14  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p3[1]}]
set_property -dict { PACKAGE_PIN G16  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p3[6]}]
set_property -dict { PACKAGE_PIN E15  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p2[1]}]
set_property -dict { PACKAGE_PIN D12  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p1[3]}]
set_property -dict { PACKAGE_PIN B11  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p1[7]}]
set_property -dict { PACKAGE_PIN A15  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p2[7]}]
set_property -dict { PACKAGE_PIN B18  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p2[3]}]
set_property -dict { PACKAGE_PIN F14  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p1[6]}]
set_property -dict { PACKAGE_PIN F13  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p1[5]}]
set_property -dict { PACKAGE_PIN D13  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p1[4]}]
set_property -dict { PACKAGE_PIN B17  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p1[2]}]
set_property -dict { PACKAGE_PIN B16  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p1[1]}]
set_property -dict { PACKAGE_PIN A16  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p1[0]}]
set_property -dict { PACKAGE_PIN A14  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p2[6]}]
set_property -dict { PACKAGE_PIN A13  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p2[5]}]
set_property -dict { PACKAGE_PIN A18  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p2[4]}]
set_property -dict { PACKAGE_PIN E16  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p2[2]}]
set_property -dict { PACKAGE_PIN C15  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p2[0]}]
set_property -dict { PACKAGE_PIN D15  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p3[7]}]
set_property -dict { PACKAGE_PIN H16  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p3[5]}]
set_property -dict { PACKAGE_PIN F16  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p3[4]}]
set_property -dict { PACKAGE_PIN F15  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p3[3]}]
set_property -dict { PACKAGE_PIN G14  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p3[2]}]
set_property -dict { PACKAGE_PIN D17  IOSTANDARD LVCMOS25 }  [get_ports {dfi_wrdata_p3[0]}]
set_property -dict { PACKAGE_PIN J17  IOSTANDARD LVCMOS33 }  [get_ports dfi_wrdata_en_p0]
set_property -dict { PACKAGE_PIN F18  IOSTANDARD LVCMOS33 }  [get_ports dfi_wrdata_en_p3]
set_property -dict { PACKAGE_PIN J18  IOSTANDARD LVCMOS33 }  [get_ports dfi_wrdata_en_p1]
set_property -dict { PACKAGE_PIN G18  IOSTANDARD LVCMOS33 }  [get_ports dfi_wrdata_en_p2]
set_property -dict { PACKAGE_PIN C16  IOSTANDARD LVCMOS33 }  [get_ports enable_i]
set_property -dict { PACKAGE_PIN C17  IOSTANDARD LVCMOS33 }  [get_ports rst_i]

# output ports

set_property -dict { PACKAGE_PIN M18 IOSTANDARD LVCMOS25 } [get_ports {DQ[7]}]
set_property -dict { PACKAGE_PIN L18 IOSTANDARD LVCMOS25 } [get_ports DQ_valid]
set_property -dict { PACKAGE_PIN L16 IOSTANDARD LVCMOS25 } [get_ports {DQ[5]}]
set_property -dict { PACKAGE_PIN L15 IOSTANDARD LVCMOS25 } [get_ports {DQ[6]}]
set_property -dict { PACKAGE_PIN L14 IOSTANDARD LVCMOS25 } [get_ports {DQ[4]}]
set_property -dict { PACKAGE_PIN M14 IOSTANDARD LVCMOS25 } [get_ports {DQ[3]}]
set_property -dict { PACKAGE_PIN K17 IOSTANDARD LVCMOS25 } [get_ports {DQ[2]}]
set_property -dict { PACKAGE_PIN K18 IOSTANDARD LVCMOS25 } [get_ports {DQ[1]}]
set_property -dict { PACKAGE_PIN R11 IOSTANDARD LVCMOS25 } [get_ports {DQ[0]}]
set_property -dict { PACKAGE_PIN V14 IOSTANDARD LVCMOS25 } [get_ports {DQS[1]}]
set_property -dict { PACKAGE_PIN V10 IOSTANDARD LVCMOS25 } [get_ports {DQS[0]}]
set_property -dict { PACKAGE_PIN V11 IOSTANDARD LVCMOS25 } [get_ports DQS_valid]
set_property -dict { PACKAGE_PIN P18 IOSTANDARD LVCMOS25 } [get_ports {RESET_n[0]}]
set_property -dict { PACKAGE_PIN M17 IOSTANDARD LVCMOS25 } [get_ports {DM[0]}]
set_property -dict { PACKAGE_PIN N17 IOSTANDARD LVCMOS25 } [get_ports {RESET_n[1]}]


